apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pardis-mcp.fullname" . }}
  labels:
    {{- include "pardis-mcp.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
